### ISSUE TITLE
[BUG]: Replies not forwarded even after PR

### ISSUE THREAD

**Issue by iiTranquility** [modmail-dev/Modmail#3351]
### Bot Version

4.1.0

### How are you hosting Modmail?

Heroku

### Error Logs

N/A, doing the online @modmail (replacing username with own) doesn't give output

### Screenshots

![image](https://github.com/user-attachments/assets/f15f2b43-a986-47e5-81d5-03bdf8e20a2e)
![image](https://github.com/user-attachments/assets/3d9839ff-1ae5-4bf8-9da9-28ccf98549fb)

### Additional Information

It was recently updated by our owner, but this still isn't working.
Please let me know what else I should do.

**Comment by iiTranquility** [comment]
`  File "/app/bot.py", line 1205, in on_typing
    await thread.channel.typing()
  File "/app/.heroku/python/lib/python3.10/site-packages/discord/context_managers.py", line 67, in wrapped_typer
    await channel._state.http.send_typing(channel.id)
  File "/app/.heroku/python/lib/python3.10/site-packages/discord/http.py", line 625, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/app/.heroku/python/lib/python3.10/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
  File "/app/.heroku/python/lib/python3.10/site-packages/aiohttp/client.py", line 601, in _request
    await resp.start(conn)
  File "/app/.heroku/python/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 965, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/app/.heroku/python/lib/python3.10/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
2024-09-30 09:06:48 discord.gateway[566] - INFO: Shard ID None has successfully RESUMED session 243f72649c0c2c803661520815b01123.
2024-09-30 09:10:14 discord.gateway[566] - INFO: Shard ID None has successfully RESUMED session 243f72649c0c2c803661520815b01123.`

Page 3 of debug logs

`2024-09-30 04:31:42 discord.gateway[566] - INFO: Shard ID None has successfully RESUMED session 243f72649c0c2c803661520815b01123.
2024-09-30 06:56:43 discord.gateway[566] - INFO: Shard ID None has successfully RESUMED session 243f72649c0c2c803661520815b01123.
2024-09-30 07:41:24 discord.gateway[566] - INFO: Shard ID None has successfully RESUMED session 243f72649c0c2c803661520815b01123.
2024-09-30 08:31:35 discord.gateway[566] - INFO: Shard ID None has successfully RESUMED session 243f72649c0c2c803661520815b01123.
2024-09-30 08:32:01 __main__[1545] - WARNING: User iitranquility does not have permission to use this command: `debug hastebin` (OWNER).
2024-09-30 08:32:01 __main__[1551] - WARNING: CheckFailure: The check functions for command debug hastebin failed.
2024-09-30 08:32:05 __main__[1545] - WARNING: User iitranquility does not have permission to use this command: `debug hastebin` (OWNER).
2024-09-30 08:32:05 __main__[1551] - WARNING: CheckFailure: The check functions for command debug hastebin failed.
2024-09-30 08:32:15 __main__[1545] - WARNING: User iitranquility does not have permission to use this command: `debug` (OWNER).
2024-09-30 08:32:15 __main__[1551] - WARNING: CheckFailure: The check functions for command debug failed.
2024-09-30 08:37:06 discord.gateway[566] - INFO: Shard ID None has successfully RESUMED session 243f72649c0c2c803661520815b01123.
2024-09-30 08:50:38 discord.gateway[566] - INFO: Shard ID None has successfully RESUMED session 243f72649c0c2c803661520815b01123.
2024-09-30 08:56:50 discord.gateway[566] - INFO: Shard ID None has successfully RESUMED session 243f72649c0c2c803661520815b01123.
2024-09-30 09:06:47 __main__[1507] - ERROR: Ignoring exception in on_typing.
2024-09-30 09:06:47 __main__[1508] - ERROR: Unexpected exception:
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)`
    
    Page 2
    
    `2024-09-30 03:36:46 core.models[324] - INFO: Discord logging level: INFO.
2024-09-30 03:36:46 __main__[165] - INFO: -------------------------
2024-09-30 03:36:46 __main__[166] - INFO: ┌┬┐┌─┐┌┬┐┌┬┐┌─┐┬┬
2024-09-30 03:36:46 __main__[167] - INFO: ││││ │ │││││├─┤││
2024-09-30 03:36:46 __main__[168] - INFO: ┴ ┴└─┘─┴┘┴ ┴┴ ┴┴┴─┘
2024-09-30 03:36:46 __main__[169] - INFO: v4.1.0
2024-09-30 03:36:46 __main__[170] - INFO: Authors: kyb3r, fourjr, Taaku18
2024-09-30 03:36:46 __main__[171] - INFO: -------------------------
2024-09-30 03:36:46 __main__[172] - INFO: discord.py: v2.3.2
2024-09-30 03:36:46 __main__[173] - INFO: -------------------------
2024-09-30 03:36:46 __main__[218] - INFO: Starting bot without presence intent.
2024-09-30 03:36:46 discord.client[603] - INFO: logging in using static token
2024-09-30 03:36:46 discord.gateway[561] - INFO: Shard ID None has connected to Gateway (Session ID: 243f72649c0c2c803661520815b01123).
2024-09-30 03:36:48 cogs.utility[629] - INFO: -------------------------
2024-09-30 03:36:48 cogs.utility[638] - INFO: Activity set to: Streaming DM for Support.
2024-09-30 03:36:48 cogs.utility[643] - INFO: Status set to: dnd.
2024-09-30 03:36:48 __main__[527] - INFO: -------------------------
2024-09-30 03:36:48 __main__[529] - INFO: Logged in as: PhoenixAC Support#2547
2024-09-30 03:36:48 __main__[530] - INFO: Bot ID: 799499251058737165
2024-09-30 03:36:48 __main__[534] - INFO: Owners: devoxi, element9, peloto
2024-09-30 03:36:48 __main__[535] - INFO: Prefix: !
2024-09-30 03:36:48 __main__[536] - INFO: Guild Name: phoenix-ac.com
2024-09-30 03:36:48 __main__[537] - INFO: Guild ID: 799493201387061259
2024-09-30 03:36:48 __main__[540] - INFO: -------------------------
2024-09-30 03:36:48 __main__[553] - INFO: There are 0 thread(s) pending to be closed.
2024-09-30 03:36:48 __main__[554] - INFO: -------------------------
2024-09-30 04:06:48 cogs.utility[648] - INFO: Starting presence loop.`

Page 1

**Comment by martinbndr** [comment]
> Replies not forwarded even after PR
Do you mean changes to the bot by the owner?

**Comment by martinbndr** [comment]
If so we so not provide support for our bot if the source code has been changed as it's no longer the original modmail bot.

**Comment by iiTranquility** [comment]
Nono the PR that fixes replies

> > Replies not forwarded even after PR
> 
> Do you mean changes to the bot by the owner?
https://github.com/modmail-dev/modmail/pull/3239

this one

**Comment by martinbndr** [comment]
Have you tried to restart the bot, so turning off the Dyno on heroku and turning it back on after a while? Can you try that and see if the issue persists.

**Comment by iiTranquility** [comment]
Yee it was recently updated and restarted etc.
But replies aren't forwarded to the bot.

**Comment by martinbndr** [comment]
Wondering why we see the messages from the user sent in the screenshot in the bot embeds. Can you reproduce the issue and then use `?debug hastebin` and send the link here.

**Comment by StephenDaDev** [comment]
I have tested this issue and have been unable to reproduce using a 4.1.0 or 4.1.1 instance. Additionally the author of the issue has not replied with logs. 

On a personal note I also think that based on the example provided, even if this was reproducible, it would be a very uncommon issue to encounter, the Discord client actually makes it somewhat difficult to reply to a message from yourself.

**Comment by iiTranquility** [comment]
Apologies to re-open this, the bot is currently 4.1.2, has been restarted recently as well.
https://hastebin.cc/rixekazine is debug logs
Below is the screenshot from the ticket creator
Discord makes it super easy to reply to your own messages.
![Image](https://github.com/user-attachments/assets/f5d1088e-f051-45e4-b6e7-be6d825bae45)

Below is from the ticket itself, replies aren't shown.
![Image](https://github.com/user-attachments/assets/b578f1c9-6675-4a3a-b067-e1faab25a962)

**Comment by StephenDaDev** [comment]
@iiTranquility I am not sure I understand what you are saying. My understanding was that the alleged bug was that when you reply to a message that it is not forwarded to the thread. However, the screenshots you provided show 3/3 messages being forwarded into the thread?

**Comment by sebkuip** [comment]
Discord replies aren’t shown in modmail threads indeed. That’s just not a feature. Not a bug as this is just how the bot works.
